// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentProgressTracker.Infrastructure;

#nullable disable

namespace StudentProgressTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250712134016_SeedDataInit")]
    partial class SeedDataInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentId", "ActivityDate");

                    b.ToTable("ActivityLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityDate = new DateTime(2025, 7, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Video Lecture",
                            CreatedAt = new DateTime(2025, 7, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Watched 'Introduction to Algebra' video.",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActivityDate = new DateTime(2025, 7, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Practice Problems",
                            CreatedAt = new DateTime(2025, 7, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Completed practice set 1 for equations.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            ActivityDate = new DateTime(2025, 7, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Reading",
                            CreatedAt = new DateTime(2025, 7, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Read Chapter 3 of Arabic grammar textbook.",
                            Duration = new TimeSpan(0, 0, 45, 0, 0),
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 4,
                            ActivityDate = new DateTime(2025, 7, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Online Quiz",
                            CreatedAt = new DateTime(2025, 7, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Attempted photosynthesis quiz.",
                            Duration = new TimeSpan(0, 0, 20, 0, 0),
                            StudentId = 4,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 5,
                            ActivityDate = new DateTime(2025, 7, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Virtual Lab",
                            CreatedAt = new DateTime(2025, 7, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Simulated chemical reaction experiment.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            StudentId = 4,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            ActivityDate = new DateTime(2025, 7, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Essay Writing",
                            CreatedAt = new DateTime(2025, 7, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Drafted introductory paragraph for literature essay.",
                            Duration = new TimeSpan(0, 1, 15, 0, 0),
                            StudentId = 5,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 7,
                            ActivityDate = new DateTime(2025, 7, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Grammar Practice",
                            CreatedAt = new DateTime(2025, 7, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Completed exercises on verb tenses.",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            StudentId = 5,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 8,
                            ActivityDate = new DateTime(2025, 7, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Review Session",
                            CreatedAt = new DateTime(2025, 7, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Attended online math review session.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            StudentId = 6,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 9,
                            ActivityDate = new DateTime(2025, 7, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Research",
                            CreatedAt = new DateTime(2025, 7, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Researched climate change impacts for project.",
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            StudentId = 7,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 10,
                            ActivityDate = new DateTime(2025, 7, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Vocabulary Practice",
                            CreatedAt = new DateTime(2025, 7, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learned new Arabic vocabulary words using flashcards.",
                            Duration = new TimeSpan(0, 0, 25, 0, 0),
                            StudentId = 9,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 11,
                            ActivityDate = new DateTime(2025, 7, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Documentary Watching",
                            CreatedAt = new DateTime(2025, 7, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Watched documentary on ancient Egypt.",
                            Duration = new TimeSpan(0, 1, 45, 0, 0),
                            StudentId = 10,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 12,
                            ActivityDate = new DateTime(2025, 7, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Note Taking",
                            CreatedAt = new DateTime(2025, 7, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reviewed history notes from last week's lecture.",
                            Duration = new TimeSpan(0, 0, 40, 0, 0),
                            StudentId = 10,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 13,
                            ActivityDate = new DateTime(2025, 7, 12, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Problem Solving",
                            CreatedAt = new DateTime(2025, 7, 12, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Worked on advanced calculus problems.",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            StudentId = 12,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 14,
                            ActivityDate = new DateTime(2025, 7, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Study Break",
                            CreatedAt = new DateTime(2025, 7, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Took a short break from studying.",
                            Duration = new TimeSpan(0, 0, 15, 0, 0),
                            StudentId = 13
                        },
                        new
                        {
                            Id = 15,
                            ActivityDate = new DateTime(2025, 7, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Creative Writing",
                            CreatedAt = new DateTime(2025, 7, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wrote a short story in Arabic.",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            StudentId = 14,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 16,
                            ActivityDate = new DateTime(2025, 7, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ActivityType = "Reading",
                            CreatedAt = new DateTime(2025, 7, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Read textbook on the Roman Empire.",
                            Duration = new TimeSpan(0, 1, 10, 0, 0),
                            StudentId = 16,
                            SubjectId = 5
                        });
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("SubjectId");

                    b.HasIndex("Type");

                    b.HasIndex("StudentId", "SubjectId");

                    b.ToTable("Assessments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedAt = new DateTime(2025, 6, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 5, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 100.00m,
                            Score = 85.00m,
                            StudentId = 3,
                            SubjectId = 1,
                            Title = "Algebra Midterm Exam",
                            Type = "Test",
                            UpdatedAt = new DateTime(2025, 6, 15, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CompletedAt = new DateTime(2025, 7, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 7, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 10, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 30.00m,
                            Score = 28.00m,
                            StudentId = 3,
                            SubjectId = 1,
                            Title = "Geometry Homework 5",
                            Type = "Assignment",
                            UpdatedAt = new DateTime(2025, 7, 10, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            MaxScore = 20.00m,
                            StudentId = 3,
                            SubjectId = 1,
                            Title = "Fractions Quiz",
                            Type = "Quiz",
                            UpdatedAt = new DateTime(2025, 7, 11, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CompletedAt = new DateTime(2025, 5, 25, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 5, 26, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 100.00m,
                            Score = 92.50m,
                            StudentId = 4,
                            SubjectId = 2,
                            Title = "Photosynthesis Lab Report",
                            Type = "Project",
                            UpdatedAt = new DateTime(2025, 5, 25, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CompletedAt = new DateTime(2025, 6, 30, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 6, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 20.00m,
                            Score = 15.00m,
                            StudentId = 4,
                            SubjectId = 2,
                            Title = "Chemical Reactions Quiz",
                            Type = "Quiz",
                            UpdatedAt = new DateTime(2025, 6, 30, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 6, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            MaxScore = 100.00m,
                            StudentId = 4,
                            SubjectId = 2,
                            Title = "Physics Principles Test",
                            Type = "Test",
                            UpdatedAt = new DateTime(2025, 6, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CompletedAt = new DateTime(2025, 7, 5, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 6, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 5, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 50.00m,
                            Score = 45.00m,
                            StudentId = 5,
                            SubjectId = 4,
                            Title = "Essay: My Favorite Book",
                            Type = "Assignment",
                            UpdatedAt = new DateTime(2025, 7, 5, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CompletedAt = new DateTime(2025, 6, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 5, 28, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 20.00m,
                            Score = 18.00m,
                            StudentId = 5,
                            SubjectId = 4,
                            Title = "Grammar Quiz 2",
                            Type = "Quiz",
                            UpdatedAt = new DateTime(2025, 6, 1, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CompletedAt = new DateTime(2025, 6, 1, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 5, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 100.00m,
                            Score = 70.00m,
                            StudentId = 6,
                            SubjectId = 1,
                            Title = "Basic Arithmetic Test",
                            Type = "Test",
                            UpdatedAt = new DateTime(2025, 6, 1, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CompletedAt = new DateTime(2025, 7, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 6, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 9, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 100.00m,
                            Score = 95.00m,
                            StudentId = 7,
                            SubjectId = 2,
                            Title = "Ecosystems Project",
                            Type = "Project",
                            UpdatedAt = new DateTime(2025, 7, 8, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CompletedAt = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 6, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 20.00m,
                            Score = 10.00m,
                            StudentId = 8,
                            SubjectId = 4,
                            Title = "Reading Comprehension Quiz",
                            Type = "Quiz",
                            UpdatedAt = new DateTime(2025, 7, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CompletedAt = new DateTime(2025, 6, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 5, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 100.00m,
                            Score = 75.00m,
                            StudentId = 9,
                            SubjectId = 3,
                            Title = "Arabic Grammar Midterm",
                            Type = "Test",
                            UpdatedAt = new DateTime(2025, 6, 10, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 7, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 25, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            MaxScore = 100.00m,
                            StudentId = 10,
                            SubjectId = 5,
                            Title = "World War II Presentation",
                            Type = "Project",
                            UpdatedAt = new DateTime(2025, 7, 5, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CompletedAt = new DateTime(2025, 7, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 7, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 11, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 100.00m,
                            Score = 98.00m,
                            StudentId = 12,
                            SubjectId = 1,
                            Title = "Calculus Practice Set",
                            Type = "Assignment",
                            UpdatedAt = new DateTime(2025, 7, 11, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CompletedAt = new DateTime(2025, 6, 28, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 6, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 6, 28, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 80.00m,
                            Score = 70.00m,
                            StudentId = 14,
                            SubjectId = 3,
                            Title = "Poetry Analysis",
                            Type = "Assignment",
                            UpdatedAt = new DateTime(2025, 6, 28, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 7, 9, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 12, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            MaxScore = 25.00m,
                            StudentId = 15,
                            SubjectId = 2,
                            Title = "Biology Chapter Quiz",
                            Type = "Quiz",
                            UpdatedAt = new DateTime(2025, 7, 9, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CompletedAt = new DateTime(2025, 5, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 4, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 5, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            MaxScore = 100.00m,
                            Score = 95.00m,
                            StudentId = 16,
                            SubjectId = 5,
                            Title = "Ancient Civilizations Test",
                            Type = "Test",
                            UpdatedAt = new DateTime(2025, 5, 10, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 6, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2025, 7, 5, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            MaxScore = 75.00m,
                            StudentId = 19,
                            SubjectId = 4,
                            Title = "Short Story Creative Writing",
                            Type = "Project",
                            UpdatedAt = new DateTime(2025, 6, 15, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.StudentProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletedAssignments")
                        .HasColumnType("int");

                    b.Property<decimal>("CompletionPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PerformanceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("time");

                    b.Property<int>("TotalAssignments")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompletionPercentage");

                    b.HasIndex("LastActivity");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentId", "SubjectId")
                        .IsUnique();

                    b.ToTable("StudentProgress");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedAssignments = 15,
                            CompletionPercentage = 75.50m,
                            CreatedAt = new DateTime(2025, 4, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3384),
                            LastActivity = new DateTime(2025, 7, 7, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3380),
                            PerformanceScore = 82.00m,
                            StudentId = 3,
                            SubjectId = 1,
                            TimeSpent = new TimeSpan(1, 21, 0, 0, 0),
                            TotalAssignments = 20,
                            UpdatedAt = new DateTime(2025, 7, 11, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3388)
                        },
                        new
                        {
                            Id = 2,
                            CompletedAssignments = 18,
                            CompletionPercentage = 90.00m,
                            CreatedAt = new DateTime(2025, 4, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3393),
                            LastActivity = new DateTime(2025, 7, 10, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3392),
                            PerformanceScore = 95.00m,
                            StudentId = 3,
                            SubjectId = 3,
                            TimeSpent = new TimeSpan(2, 12, 0, 0, 0),
                            TotalAssignments = 18,
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3393)
                        },
                        new
                        {
                            Id = 3,
                            CompletedAssignments = 10,
                            CompletionPercentage = 60.25m,
                            CreatedAt = new DateTime(2025, 1, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3396),
                            LastActivity = new DateTime(2025, 7, 2, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3396),
                            PerformanceScore = 70.50m,
                            StudentId = 4,
                            SubjectId = 2,
                            TimeSpent = new TimeSpan(1, 6, 0, 0, 0),
                            TotalAssignments = 20,
                            UpdatedAt = new DateTime(2025, 7, 9, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3397)
                        },
                        new
                        {
                            Id = 4,
                            CompletedAssignments = 12,
                            CompletionPercentage = 85.00m,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3400),
                            LastActivity = new DateTime(2025, 7, 11, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3399),
                            PerformanceScore = 88.00m,
                            StudentId = 5,
                            SubjectId = 4,
                            TimeSpent = new TimeSpan(2, 2, 0, 0, 0),
                            TotalAssignments = 15,
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3400)
                        },
                        new
                        {
                            Id = 5,
                            CompletedAssignments = 8,
                            CompletionPercentage = 50.00m,
                            CreatedAt = new DateTime(2025, 5, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3403),
                            LastActivity = new DateTime(2025, 7, 5, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3402),
                            PerformanceScore = 65.00m,
                            StudentId = 6,
                            SubjectId = 1,
                            TimeSpent = new TimeSpan(1, 1, 0, 0, 0),
                            TotalAssignments = 16,
                            UpdatedAt = new DateTime(2025, 7, 10, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3403)
                        },
                        new
                        {
                            Id = 6,
                            CompletedAssignments = 14,
                            CompletionPercentage = 70.00m,
                            CreatedAt = new DateTime(2025, 5, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3407),
                            LastActivity = new DateTime(2025, 7, 9, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3406),
                            PerformanceScore = 75.00m,
                            StudentId = 6,
                            SubjectId = 3,
                            TimeSpent = new TimeSpan(1, 16, 0, 0, 0),
                            TotalAssignments = 20,
                            UpdatedAt = new DateTime(2025, 7, 11, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3407)
                        },
                        new
                        {
                            Id = 7,
                            CompletedAssignments = 19,
                            CompletionPercentage = 95.00m,
                            CreatedAt = new DateTime(2025, 2, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3412),
                            LastActivity = new DateTime(2025, 7, 12, 1, 40, 16, 201, DateTimeKind.Utc).AddTicks(3410),
                            PerformanceScore = 92.00m,
                            StudentId = 7,
                            SubjectId = 2,
                            TimeSpent = new TimeSpan(2, 22, 0, 0, 0),
                            TotalAssignments = 20,
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3412)
                        },
                        new
                        {
                            Id = 8,
                            CompletedAssignments = 6,
                            CompletionPercentage = 40.00m,
                            CreatedAt = new DateTime(2024, 12, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3415),
                            LastActivity = new DateTime(2025, 6, 27, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3415),
                            PerformanceScore = 55.00m,
                            StudentId = 8,
                            SubjectId = 4,
                            TimeSpent = new TimeSpan(0, 20, 0, 0, 0),
                            TotalAssignments = 15,
                            UpdatedAt = new DateTime(2025, 7, 7, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3416)
                        },
                        new
                        {
                            Id = 9,
                            CompletedAssignments = 17,
                            CompletionPercentage = 80.00m,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3418),
                            LastActivity = new DateTime(2025, 7, 8, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3418),
                            PerformanceScore = 88.00m,
                            StudentId = 9,
                            SubjectId = 1,
                            TimeSpent = new TimeSpan(2, 7, 0, 0, 0),
                            TotalAssignments = 20,
                            UpdatedAt = new DateTime(2025, 7, 11, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3419)
                        },
                        new
                        {
                            Id = 10,
                            CompletedAssignments = 13,
                            CompletionPercentage = 65.00m,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3423),
                            LastActivity = new DateTime(2025, 7, 6, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3422),
                            PerformanceScore = 72.00m,
                            StudentId = 9,
                            SubjectId = 3,
                            TimeSpent = new TimeSpan(1, 11, 0, 0, 0),
                            TotalAssignments = 20,
                            UpdatedAt = new DateTime(2025, 7, 10, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3423)
                        },
                        new
                        {
                            Id = 11,
                            CompletedAssignments = 16,
                            CompletionPercentage = 78.00m,
                            CreatedAt = new DateTime(2025, 4, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3426),
                            LastActivity = new DateTime(2025, 7, 10, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3425),
                            PerformanceScore = 85.00m,
                            StudentId = 10,
                            SubjectId = 2,
                            TimeSpent = new TimeSpan(2, 0, 0, 0, 0),
                            TotalAssignments = 20,
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3426)
                        },
                        new
                        {
                            Id = 12,
                            CompletedAssignments = 10,
                            CompletionPercentage = 92.00m,
                            CreatedAt = new DateTime(2025, 4, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3429),
                            LastActivity = new DateTime(2025, 7, 11, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3429),
                            PerformanceScore = 90.00m,
                            StudentId = 10,
                            SubjectId = 5,
                            TimeSpent = new TimeSpan(2, 7, 0, 0, 0),
                            TotalAssignments = 10,
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3430)
                        },
                        new
                        {
                            Id = 13,
                            CompletedAssignments = 3,
                            CompletionPercentage = 20.00m,
                            CreatedAt = new DateTime(2025, 6, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3432),
                            LastActivity = new DateTime(2025, 6, 22, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3432),
                            PerformanceScore = 40.00m,
                            StudentId = 11,
                            SubjectId = 4,
                            TimeSpent = new TimeSpan(0, 10, 0, 0, 0),
                            TotalAssignments = 15,
                            UpdatedAt = new DateTime(2025, 7, 2, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3433)
                        },
                        new
                        {
                            Id = 14,
                            CompletedAssignments = 18,
                            CompletionPercentage = 88.00m,
                            CreatedAt = new DateTime(2025, 2, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3436),
                            LastActivity = new DateTime(2025, 7, 11, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3435),
                            PerformanceScore = 91.00m,
                            StudentId = 12,
                            SubjectId = 1,
                            TimeSpent = new TimeSpan(2, 12, 0, 0, 0),
                            TotalAssignments = 20,
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3436)
                        },
                        new
                        {
                            Id = 15,
                            CompletedAssignments = 1,
                            CompletionPercentage = 10.00m,
                            CreatedAt = new DateTime(2025, 5, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3439),
                            LastActivity = new DateTime(2025, 6, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3438),
                            PerformanceScore = 30.00m,
                            StudentId = 13,
                            SubjectId = 6,
                            TimeSpent = new TimeSpan(0, 5, 0, 0, 0),
                            TotalAssignments = 10,
                            UpdatedAt = new DateTime(2025, 6, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3440)
                        },
                        new
                        {
                            Id = 16,
                            CompletedAssignments = 14,
                            CompletionPercentage = 70.00m,
                            CreatedAt = new DateTime(2025, 4, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3442),
                            LastActivity = new DateTime(2025, 7, 9, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3442),
                            PerformanceScore = 78.00m,
                            StudentId = 14,
                            SubjectId = 3,
                            TimeSpent = new TimeSpan(1, 18, 0, 0, 0),
                            TotalAssignments = 20,
                            UpdatedAt = new DateTime(2025, 7, 11, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3443)
                        },
                        new
                        {
                            Id = 17,
                            CompletedAssignments = 9,
                            CompletionPercentage = 55.00m,
                            CreatedAt = new DateTime(2025, 6, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3446),
                            LastActivity = new DateTime(2025, 7, 4, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3445),
                            PerformanceScore = 62.00m,
                            StudentId = 15,
                            SubjectId = 2,
                            TimeSpent = new TimeSpan(1, 4, 0, 0, 0),
                            TotalAssignments = 20,
                            UpdatedAt = new DateTime(2025, 7, 8, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3446)
                        },
                        new
                        {
                            Id = 18,
                            CompletedAssignments = 19,
                            CompletionPercentage = 98.00m,
                            CreatedAt = new DateTime(2025, 1, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3449),
                            LastActivity = new DateTime(2025, 7, 11, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3449),
                            PerformanceScore = 99.00m,
                            StudentId = 16,
                            SubjectId = 5,
                            TimeSpent = new TimeSpan(3, 3, 0, 0, 0),
                            TotalAssignments = 19,
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3450)
                        },
                        new
                        {
                            Id = 19,
                            CompletedAssignments = 5,
                            CompletionPercentage = 35.00m,
                            CreatedAt = new DateTime(2025, 6, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3453),
                            LastActivity = new DateTime(2025, 6, 30, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3452),
                            PerformanceScore = 48.00m,
                            StudentId = 17,
                            SubjectId = 4,
                            TimeSpent = new TimeSpan(0, 18, 0, 0, 0),
                            TotalAssignments = 15,
                            UpdatedAt = new DateTime(2025, 7, 7, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3453)
                        },
                        new
                        {
                            Id = 20,
                            CompletedAssignments = 14,
                            CompletionPercentage = 72.00m,
                            CreatedAt = new DateTime(2025, 3, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3456),
                            LastActivity = new DateTime(2025, 7, 6, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3455),
                            PerformanceScore = 79.00m,
                            StudentId = 18,
                            SubjectId = 1,
                            TimeSpent = new TimeSpan(1, 16, 0, 0, 0),
                            TotalAssignments = 20,
                            UpdatedAt = new DateTime(2025, 7, 10, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3456)
                        });
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3253),
                            Description = "Covers fundamental concepts of algebra, geometry, and arithmetic.",
                            IsActive = true,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3257),
                            Description = "An introduction to biology, chemistry, and physics.",
                            IsActive = true,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3259),
                            Description = "Focuses on Arabic grammar, literature, and composition.",
                            IsActive = true,
                            Name = "Arabic Language"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3260),
                            Description = "Develops skills in reading, writing, and speaking English.",
                            IsActive = true,
                            Name = "English Language"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3262),
                            Description = "A study of major world events and civilizations.",
                            IsActive = true,
                            Name = "History"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3264),
                            Description = "Learning the basics of programming and computational thinking.",
                            IsActive = false,
                            Name = "Computer Science"
                        });
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.TeacherStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "StudentId", "SubjectId")
                        .IsUnique();

                    b.ToTable("TeacherStudents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StudentId = 3,
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StudentId = 6,
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 3,
                            AssignedDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StudentId = 9,
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 4,
                            AssignedDate = new DateTime(2022, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StudentId = 4,
                            SubjectId = 2,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 5,
                            AssignedDate = new DateTime(2022, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StudentId = 7,
                            SubjectId = 2,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 6,
                            AssignedDate = new DateTime(2022, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StudentId = 10,
                            SubjectId = 2,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 7,
                            AssignedDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StudentId = 3,
                            SubjectId = 3,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 8,
                            AssignedDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StudentId = 6,
                            SubjectId = 3,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 9,
                            AssignedDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StudentId = 9,
                            SubjectId = 3,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 10,
                            AssignedDate = new DateTime(2021, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StudentId = 5,
                            SubjectId = 4,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 11,
                            AssignedDate = new DateTime(2021, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StudentId = 8,
                            SubjectId = 4,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 12,
                            AssignedDate = new DateTime(2021, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StudentId = 11,
                            SubjectId = 4,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 13,
                            AssignedDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            StudentId = 13,
                            SubjectId = 6,
                            TeacherId = 2
                        });
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Grade");

                    b.HasIndex("LastActivityDate");

                    b.HasIndex("Role");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3026),
                            Email = "teacher1@example.com",
                            FirstName = "Ali",
                            LastName = "Hassan",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Teacher",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3027)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3037),
                            Email = "teacher2@example.com",
                            FirstName = "Sara",
                            LastName = "Ibrahim",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Teacher",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3037)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3045),
                            Email = "student1@example.com",
                            EnrollmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Omar",
                            Grade = 3,
                            LastName = "Nabil",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3045)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3048),
                            Email = "student2@example.com",
                            EnrollmentDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Laila",
                            Grade = 4,
                            LastName = "Adel",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3048)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3051),
                            Email = "student3@example.com",
                            EnrollmentDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Youssef",
                            Grade = 5,
                            LastName = "Khaled",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3051)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3055),
                            Email = "student4@example.com",
                            EnrollmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Fatima",
                            Grade = 3,
                            LastName = "Gamal",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3056)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3058),
                            Email = "student5@example.com",
                            EnrollmentDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Karim",
                            Grade = 4,
                            LastName = "Samir",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3059)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3061),
                            Email = "student6@example.com",
                            EnrollmentDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hania",
                            Grade = 5,
                            LastName = "Tarek",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3061)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3065),
                            Email = "student7@example.com",
                            EnrollmentDate = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ziad",
                            Grade = 6,
                            LastName = "Ashraf",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3065)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3113),
                            Email = "student8@example.com",
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Salma",
                            Grade = 2,
                            LastName = "Ehab",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3113)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3116),
                            Email = "student9@example.com",
                            EnrollmentDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ahmed",
                            Grade = 1,
                            LastName = "Said",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3116)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3119),
                            Email = "student10@example.com",
                            EnrollmentDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nour",
                            Grade = 4,
                            LastName = "Walid",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3119)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3122),
                            Email = "student11@example.com",
                            EnrollmentDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mohamed",
                            Grade = 5,
                            LastName = "Sherif",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3122)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3125),
                            Email = "student12@example.com",
                            EnrollmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jana",
                            Grade = 3,
                            LastName = "Hesham",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3125)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3127),
                            Email = "student13@example.com",
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Adam",
                            Grade = 2,
                            LastName = "Medhat",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3128)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3130),
                            Email = "student14@example.com",
                            EnrollmentDate = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mariam",
                            Grade = 6,
                            LastName = "Fares",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3131)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3133),
                            Email = "student15@example.com",
                            EnrollmentDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ibrahim",
                            Grade = 1,
                            LastName = "Amr",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3133)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3137),
                            Email = "student16@example.com",
                            EnrollmentDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Farida",
                            Grade = 5,
                            LastName = "Hossam",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3137)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3140),
                            Email = "student17@example.com",
                            EnrollmentDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mostafa",
                            Grade = 4,
                            LastName = "Maher",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3140)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3143),
                            Email = "student18@example.com",
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hana",
                            Grade = 2,
                            LastName = "Ismail",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3143)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3146),
                            Email = "student19@example.com",
                            EnrollmentDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Yassin",
                            Grade = 3,
                            LastName = "Tamer",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3146)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3149),
                            Email = "student20@example.com",
                            EnrollmentDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Malak",
                            Grade = 1,
                            LastName = "Wael",
                            PasswordHash = "AQAAAAIAAYagAAAAEOb7wmyh/dP4G9igDpJzDsbcRrVTv7U6kJyUfS1DATRmi2VvSJIAY9+ntRx2yVe1aQ==",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 7, 12, 13, 40, 16, 201, DateTimeKind.Utc).AddTicks(3149)
                        });
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.ActivityLog", b =>
                {
                    b.HasOne("StudentProgressTracker.Domain.Entities.User", "Student")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentProgressTracker.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("StudentProgressTracker.Domain.Entities.User", "Student")
                        .WithMany("StudentAssessments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentProgressTracker.Domain.Entities.Subject", "Subject")
                        .WithMany("Assessments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("StudentProgressTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.StudentProgress", b =>
                {
                    b.HasOne("StudentProgressTracker.Domain.Entities.User", "Student")
                        .WithMany("StudentProgress")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentProgressTracker.Domain.Entities.Subject", "Subject")
                        .WithMany("StudentProgress")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.TeacherStudent", b =>
                {
                    b.HasOne("StudentProgressTracker.Domain.Entities.User", "Student")
                        .WithMany("StudentAssignments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentProgressTracker.Domain.Entities.Subject", "Subject")
                        .WithMany("TeacherStudents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentProgressTracker.Domain.Entities.User", "Teacher")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("StudentProgress");

                    b.Navigation("TeacherStudents");
                });

            modelBuilder.Entity("StudentProgressTracker.Domain.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("StudentAssessments");

                    b.Navigation("StudentAssignments");

                    b.Navigation("StudentProgress");

                    b.Navigation("TeacherAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
